# Generated by Django 4.0.2 on 2022-02-07 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('delivered_at', models.DateTimeField(verbose_name='delivered_at')),
                ('is_delivered', models.BooleanField()),
                ('paid_at', models.DateTimeField(verbose_name='paid_at')),
                ('is_paid', models.BooleanField()),
                ('payment_method', models.CharField(max_length=255, verbose_name='payment_method')),
                ('tax_price', models.CharField(max_length=255, verbose_name='tax_price')),
                ('total_price', models.CharField(max_length=255, verbose_name='total_price')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('postal_code', models.CharField(max_length=255, verbose_name='postal_code')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('chipping_price', models.CharField(max_length=255, verbose_name='shipping_price')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('qty', models.IntegerField()),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('image', models.CharField(max_length=255, verbose_name='image')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_item', to='product.product')),
            ],
        ),
    ]
